//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.16 at 11:01:53 AM IST 
//


package com.example.genericrestapi.factory;

import org.springframework.beans.factory.annotation.Autowired;
import com.example.genericrestapi.service.SRLDiagnosticService;

public class DiagnosticsFactory extends BaseFactory{
	
	@Autowired
	SRLDiagnosticService srlDiagnosticService;
	
	@Override
	public Diagnostics createDiagnostics(Long type) {
		Diagnostics diagnostics;
        switch (type.intValue())
        {
            case 1://SRL
            	diagnostics = srlDiagnosticService;
                break;
//            case 2:
//            	diagnostics = srlDiagnostics;
//                break;
//            case 3:
//            	diagnostics =  srlDiagnosticService;
//                break;
            default: throw new IllegalArgumentException("No such Diagnostics.");
        }
        return diagnostics;
	}
	
}


