//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.30 at 06:58:36 PM IST 
//


package com.example.genericrestapi.createOrder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.genericrestapi.createOrder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _String_QNAME = new QName("http://tempuri.org/", "string");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.genericrestapi.createOrder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticateUser }
     * 
     */
    public AuthenticateUser createAuthenticateUser() {
        return new AuthenticateUser();
    }

    /**
     * Create an instance of {@link AuthenticateUserResponse }
     * 
     */
    public AuthenticateUserResponse createAuthenticateUserResponse() {
        return new AuthenticateUserResponse();
    }

    /**
     * Create an instance of {@link AuthenticateUserNew }
     * 
     */
    public AuthenticateUserNew createAuthenticateUserNew() {
        return new AuthenticateUserNew();
    }

    /**
     * Create an instance of {@link AuthenticateUserNewResponse }
     * 
     */
    public AuthenticateUserNewResponse createAuthenticateUserNewResponse() {
        return new AuthenticateUserNewResponse();
    }

    /**
     * Create an instance of {@link CancelOrder }
     * 
     */
    public CancelOrder createCancelOrder() {
        return new CancelOrder();
    }

    /**
     * Create an instance of {@link CancelOrderResponse }
     * 
     */
    public CancelOrderResponse createCancelOrderResponse() {
        return new CancelOrderResponse();
    }

    /**
     * Create an instance of {@link ChangePassword }
     * 
     */
    public ChangePassword createChangePassword() {
        return new ChangePassword();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     * 
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link CreateOrderGuestSurvey }
     * 
     */
    public CreateOrderGuestSurvey createCreateOrderGuestSurvey() {
        return new CreateOrderGuestSurvey();
    }

    /**
     * Create an instance of {@link CreateOrderGuestSurveyResponse }
     * 
     */
    public CreateOrderGuestSurveyResponse createCreateOrderGuestSurveyResponse() {
        return new CreateOrderGuestSurveyResponse();
    }

    /**
     * Create an instance of {@link CreateOrderGuestSurveyNew }
     * 
     */
    public CreateOrderGuestSurveyNew createCreateOrderGuestSurveyNew() {
        return new CreateOrderGuestSurveyNew();
    }

    /**
     * Create an instance of {@link CreateOrderGuestSurveyNewResponse }
     * 
     */
    public CreateOrderGuestSurveyNewResponse createCreateOrderGuestSurveyNewResponse() {
        return new CreateOrderGuestSurveyNewResponse();
    }

    /**
     * Create an instance of {@link CreateOrderOPT }
     * 
     */
    public CreateOrderOPT createCreateOrderOPT() {
        return new CreateOrderOPT();
    }

    /**
     * Create an instance of {@link CreateOrderOPTResponse }
     * 
     */
    public CreateOrderOPTResponse createCreateOrderOPTResponse() {
        return new CreateOrderOPTResponse();
    }

    /**
     * Create an instance of {@link CreateOrderGuestCC }
     * 
     */
    public CreateOrderGuestCC createCreateOrderGuestCC() {
        return new CreateOrderGuestCC();
    }

    /**
     * Create an instance of {@link CreateOrderGuestCCResponse }
     * 
     */
    public CreateOrderGuestCCResponse createCreateOrderGuestCCResponse() {
        return new CreateOrderGuestCCResponse();
    }

    /**
     * Create an instance of {@link CreateOrderGuestCCNew }
     * 
     */
    public CreateOrderGuestCCNew createCreateOrderGuestCCNew() {
        return new CreateOrderGuestCCNew();
    }

    /**
     * Create an instance of {@link CreateOrderGuestCCNewResponse }
     * 
     */
    public CreateOrderGuestCCNewResponse createCreateOrderGuestCCNewResponse() {
        return new CreateOrderGuestCCNewResponse();
    }

    /**
     * Create an instance of {@link DeleteNotification }
     * 
     */
    public DeleteNotification createDeleteNotification() {
        return new DeleteNotification();
    }

    /**
     * Create an instance of {@link DeleteNotificationResponse }
     * 
     */
    public DeleteNotificationResponse createDeleteNotificationResponse() {
        return new DeleteNotificationResponse();
    }

    /**
     * Create an instance of {@link FetchDataNew }
     * 
     */
    public FetchDataNew createFetchDataNew() {
        return new FetchDataNew();
    }

    /**
     * Create an instance of {@link FetchDataNewResponse }
     * 
     */
    public FetchDataNewResponse createFetchDataNewResponse() {
        return new FetchDataNewResponse();
    }

    /**
     * Create an instance of {@link FetchPatientDetails }
     * 
     */
    public FetchPatientDetails createFetchPatientDetails() {
        return new FetchPatientDetails();
    }

    /**
     * Create an instance of {@link FetchPatientDetailsResponse }
     * 
     */
    public FetchPatientDetailsResponse createFetchPatientDetailsResponse() {
        return new FetchPatientDetailsResponse();
    }

    /**
     * Create an instance of {@link FilterProducts }
     * 
     */
    public FilterProducts createFilterProducts() {
        return new FilterProducts();
    }

    /**
     * Create an instance of {@link FilterProductsResponse }
     * 
     */
    public FilterProductsResponse createFilterProductsResponse() {
        return new FilterProductsResponse();
    }

    /**
     * Create an instance of {@link GetAllCategories }
     * 
     */
    public GetAllCategories createGetAllCategories() {
        return new GetAllCategories();
    }

    /**
     * Create an instance of {@link GetAllCategoriesResponse }
     * 
     */
    public GetAllCategoriesResponse createGetAllCategoriesResponse() {
        return new GetAllCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetPackageDetails }
     * 
     */
    public GetPackageDetails createGetPackageDetails() {
        return new GetPackageDetails();
    }

    /**
     * Create an instance of {@link GetPackageDetailsResponse }
     * 
     */
    public GetPackageDetailsResponse createGetPackageDetailsResponse() {
        return new GetPackageDetailsResponse();
    }

    /**
     * Create an instance of {@link GetTopProducts }
     * 
     */
    public GetTopProducts createGetTopProducts() {
        return new GetTopProducts();
    }

    /**
     * Create an instance of {@link GetTopProductsResponse }
     * 
     */
    public GetTopProductsResponse createGetTopProductsResponse() {
        return new GetTopProductsResponse();
    }

    /**
     * Create an instance of {@link SearchTest }
     * 
     */
    public SearchTest createSearchTest() {
        return new SearchTest();
    }

    /**
     * Create an instance of {@link SearchTestResponse }
     * 
     */
    public SearchTestResponse createSearchTestResponse() {
        return new SearchTestResponse();
    }

    /**
     * Create an instance of {@link ForgotPassword }
     * 
     */
    public ForgotPassword createForgotPassword() {
        return new ForgotPassword();
    }

    /**
     * Create an instance of {@link ForgotPasswordResponse }
     * 
     */
    public ForgotPasswordResponse createForgotPasswordResponse() {
        return new ForgotPasswordResponse();
    }

    /**
     * Create an instance of {@link GetAllStates }
     * 
     */
    public GetAllStates createGetAllStates() {
        return new GetAllStates();
    }

    /**
     * Create an instance of {@link GetAllStatesResponse }
     * 
     */
    public GetAllStatesResponse createGetAllStatesResponse() {
        return new GetAllStatesResponse();
    }

    /**
     * Create an instance of {@link GetCities }
     * 
     */
    public GetCities createGetCities() {
        return new GetCities();
    }

    /**
     * Create an instance of {@link GetCitiesResponse }
     * 
     */
    public GetCitiesResponse createGetCitiesResponse() {
        return new GetCitiesResponse();
    }

    /**
     * Create an instance of {@link GetCityStateList }
     * 
     */
    public GetCityStateList createGetCityStateList() {
        return new GetCityStateList();
    }

    /**
     * Create an instance of {@link GetCityStateListResponse }
     * 
     */
    public GetCityStateListResponse createGetCityStateListResponse() {
        return new GetCityStateListResponse();
    }

    /**
     * Create an instance of {@link GetVersion }
     * 
     */
    public GetVersion createGetVersion() {
        return new GetVersion();
    }

    /**
     * Create an instance of {@link GetVersionResponse }
     * 
     */
    public GetVersionResponse createGetVersionResponse() {
        return new GetVersionResponse();
    }

    /**
     * Create an instance of {@link GetContent }
     * 
     */
    public GetContent createGetContent() {
        return new GetContent();
    }

    /**
     * Create an instance of {@link GetContentResponse }
     * 
     */
    public GetContentResponse createGetContentResponse() {
        return new GetContentResponse();
    }

    /**
     * Create an instance of {@link GetDownloadPromocodeNew }
     * 
     */
    public GetDownloadPromocodeNew createGetDownloadPromocodeNew() {
        return new GetDownloadPromocodeNew();
    }

    /**
     * Create an instance of {@link GetDownloadPromocodeNewResponse }
     * 
     */
    public GetDownloadPromocodeNewResponse createGetDownloadPromocodeNewResponse() {
        return new GetDownloadPromocodeNewResponse();
    }

    /**
     * Create an instance of {@link GetFeedback }
     * 
     */
    public GetFeedback createGetFeedback() {
        return new GetFeedback();
    }

    /**
     * Create an instance of {@link GetFeedbackResponse }
     * 
     */
    public GetFeedbackResponse createGetFeedbackResponse() {
        return new GetFeedbackResponse();
    }

    /**
     * Create an instance of {@link GetNotification }
     * 
     */
    public GetNotification createGetNotification() {
        return new GetNotification();
    }

    /**
     * Create an instance of {@link GetNotificationResponse }
     * 
     */
    public GetNotificationResponse createGetNotificationResponse() {
        return new GetNotificationResponse();
    }

    /**
     * Create an instance of {@link GetOrderHistoryProduct }
     * 
     */
    public GetOrderHistoryProduct createGetOrderHistoryProduct() {
        return new GetOrderHistoryProduct();
    }

    /**
     * Create an instance of {@link GetOrderHistoryProductResponse }
     * 
     */
    public GetOrderHistoryProductResponse createGetOrderHistoryProductResponse() {
        return new GetOrderHistoryProductResponse();
    }

    /**
     * Create an instance of {@link GetOrderStatus }
     * 
     */
    public GetOrderStatus createGetOrderStatus() {
        return new GetOrderStatus();
    }

    /**
     * Create an instance of {@link GetOrderStatusResponse }
     * 
     */
    public GetOrderStatusResponse createGetOrderStatusResponse() {
        return new GetOrderStatusResponse();
    }

    /**
     * Create an instance of {@link GetPatientDetails }
     * 
     */
    public GetPatientDetails createGetPatientDetails() {
        return new GetPatientDetails();
    }

    /**
     * Create an instance of {@link GetPatientDetailsResponse }
     * 
     */
    public GetPatientDetailsResponse createGetPatientDetailsResponse() {
        return new GetPatientDetailsResponse();
    }

    /**
     * Create an instance of {@link GetPromotionOffers }
     * 
     */
    public GetPromotionOffers createGetPromotionOffers() {
        return new GetPromotionOffers();
    }

    /**
     * Create an instance of {@link GetPromotionOffersResponse }
     * 
     */
    public GetPromotionOffersResponse createGetPromotionOffersResponse() {
        return new GetPromotionOffersResponse();
    }

    /**
     * Create an instance of {@link GetResultReport }
     * 
     */
    public GetResultReport createGetResultReport() {
        return new GetResultReport();
    }

    /**
     * Create an instance of {@link GetResultReportResponse }
     * 
     */
    public GetResultReportResponse createGetResultReportResponse() {
        return new GetResultReportResponse();
    }

    /**
     * Create an instance of {@link GetResultReportOPT }
     * 
     */
    public GetResultReportOPT createGetResultReportOPT() {
        return new GetResultReportOPT();
    }

    /**
     * Create an instance of {@link GetResultReportOPTResponse }
     * 
     */
    public GetResultReportOPTResponse createGetResultReportOPTResponse() {
        return new GetResultReportOPTResponse();
    }

    /**
     * Create an instance of {@link GetUser }
     * 
     */
    public GetUser createGetUser() {
        return new GetUser();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link MyCartDetails }
     * 
     */
    public MyCartDetails createMyCartDetails() {
        return new MyCartDetails();
    }

    /**
     * Create an instance of {@link MyCartDetailsResponse }
     * 
     */
    public MyCartDetailsResponse createMyCartDetailsResponse() {
        return new MyCartDetailsResponse();
    }

    /**
     * Create an instance of {@link PendingRegistration }
     * 
     */
    public PendingRegistration createPendingRegistration() {
        return new PendingRegistration();
    }

    /**
     * Create an instance of {@link PendingRegistrationResponse }
     * 
     */
    public PendingRegistrationResponse createPendingRegistrationResponse() {
        return new PendingRegistrationResponse();
    }

    /**
     * Create an instance of {@link PaymentStatusOptions }
     * 
     */
    public PaymentStatusOptions createPaymentStatusOptions() {
        return new PaymentStatusOptions();
    }

    /**
     * Create an instance of {@link PaymentStatusOptionsResponse }
     * 
     */
    public PaymentStatusOptionsResponse createPaymentStatusOptionsResponse() {
        return new PaymentStatusOptionsResponse();
    }

    /**
     * Create an instance of {@link RepeateOrder }
     * 
     */
    public RepeateOrder createRepeateOrder() {
        return new RepeateOrder();
    }

    /**
     * Create an instance of {@link RepeateOrderResponse }
     * 
     */
    public RepeateOrderResponse createRepeateOrderResponse() {
        return new RepeateOrderResponse();
    }

    /**
     * Create an instance of {@link ResendOTP }
     * 
     */
    public ResendOTP createResendOTP() {
        return new ResendOTP();
    }

    /**
     * Create an instance of {@link ResendOTPResponse }
     * 
     */
    public ResendOTPResponse createResendOTPResponse() {
        return new ResendOTPResponse();
    }

    /**
     * Create an instance of {@link SearchLocationsOnMap }
     * 
     */
    public SearchLocationsOnMap createSearchLocationsOnMap() {
        return new SearchLocationsOnMap();
    }

    /**
     * Create an instance of {@link SearchLocationsOnMapResponse }
     * 
     */
    public SearchLocationsOnMapResponse createSearchLocationsOnMapResponse() {
        return new SearchLocationsOnMapResponse();
    }

    /**
     * Create an instance of {@link TrackYourOrder }
     * 
     */
    public TrackYourOrder createTrackYourOrder() {
        return new TrackYourOrder();
    }

    /**
     * Create an instance of {@link TrackYourOrderResponse }
     * 
     */
    public TrackYourOrderResponse createTrackYourOrderResponse() {
        return new TrackYourOrderResponse();
    }

    /**
     * Create an instance of {@link UpdateProfile }
     * 
     */
    public UpdateProfile createUpdateProfile() {
        return new UpdateProfile();
    }

    /**
     * Create an instance of {@link UpdateProfileResponse }
     * 
     */
    public UpdateProfileResponse createUpdateProfileResponse() {
        return new UpdateProfileResponse();
    }

    /**
     * Create an instance of {@link UserRegistration }
     * 
     */
    public UserRegistration createUserRegistration() {
        return new UserRegistration();
    }

    /**
     * Create an instance of {@link UserRegistrationResponse }
     * 
     */
    public UserRegistrationResponse createUserRegistrationResponse() {
        return new UserRegistrationResponse();
    }

    /**
     * Create an instance of {@link ValidateVoucher }
     * 
     */
    public ValidateVoucher createValidateVoucher() {
        return new ValidateVoucher();
    }

    /**
     * Create an instance of {@link ValidateVoucherResponse }
     * 
     */
    public ValidateVoucherResponse createValidateVoucherResponse() {
        return new ValidateVoucherResponse();
    }

    /**
     * Create an instance of {@link ValidatePromocodeCART }
     * 
     */
    public ValidatePromocodeCART createValidatePromocodeCART() {
        return new ValidatePromocodeCART();
    }

    /**
     * Create an instance of {@link ValidatePromocodeCARTResponse }
     * 
     */
    public ValidatePromocodeCARTResponse createValidatePromocodeCARTResponse() {
        return new ValidatePromocodeCARTResponse();
    }

    /**
     * Create an instance of {@link ValidateRegistration }
     * 
     */
    public ValidateRegistration createValidateRegistration() {
        return new ValidateRegistration();
    }

    /**
     * Create an instance of {@link ValidateRegistrationResponse }
     * 
     */
    public ValidateRegistrationResponse createValidateRegistrationResponse() {
        return new ValidateRegistrationResponse();
    }

    /**
     * Create an instance of {@link ValidateRegistrationFamily }
     * 
     */
    public ValidateRegistrationFamily createValidateRegistrationFamily() {
        return new ValidateRegistrationFamily();
    }

    /**
     * Create an instance of {@link ValidateRegistrationFamilyResponse }
     * 
     */
    public ValidateRegistrationFamilyResponse createValidateRegistrationFamilyResponse() {
        return new ValidateRegistrationFamilyResponse();
    }

    /**
     * Create an instance of {@link GetOTP }
     * 
     */
    public GetOTP createGetOTP() {
        return new GetOTP();
    }

    /**
     * Create an instance of {@link GetOTPResponse }
     * 
     */
    public GetOTPResponse createGetOTPResponse() {
        return new GetOTPResponse();
    }

    /**
     * Create an instance of {@link VerifyOTP }
     * 
     */
    public VerifyOTP createVerifyOTP() {
        return new VerifyOTP();
    }

    /**
     * Create an instance of {@link VerifyOTPResponse }
     * 
     */
    public VerifyOTPResponse createVerifyOTPResponse() {
        return new VerifyOTPResponse();
    }

    /**
     * Create an instance of {@link GetPromocode }
     * 
     */
    public GetPromocode createGetPromocode() {
        return new GetPromocode();
    }

    /**
     * Create an instance of {@link GetPromocodeResponse }
     * 
     */
    public GetPromocodeResponse createGetPromocodeResponse() {
        return new GetPromocodeResponse();
    }

    /**
     * Create an instance of {@link GetSurvey }
     * 
     */
    public GetSurvey createGetSurvey() {
        return new GetSurvey();
    }

    /**
     * Create an instance of {@link GetSurveyResponse }
     * 
     */
    public GetSurveyResponse createGetSurveyResponse() {
        return new GetSurveyResponse();
    }

    /**
     * Create an instance of {@link GetRelationShip }
     * 
     */
    public GetRelationShip createGetRelationShip() {
        return new GetRelationShip();
    }

    /**
     * Create an instance of {@link GetRelationShipResponse }
     * 
     */
    public GetRelationShipResponse createGetRelationShipResponse() {
        return new GetRelationShipResponse();
    }

    /**
     * Create an instance of {@link ValidateMobileNo }
     * 
     */
    public ValidateMobileNo createValidateMobileNo() {
        return new ValidateMobileNo();
    }

    /**
     * Create an instance of {@link ValidateMobileNoResponse }
     * 
     */
    public ValidateMobileNoResponse createValidateMobileNoResponse() {
        return new ValidateMobileNoResponse();
    }

    /**
     * Create an instance of {@link AuthenticateMobileNo }
     * 
     */
    public AuthenticateMobileNo createAuthenticateMobileNo() {
        return new AuthenticateMobileNo();
    }

    /**
     * Create an instance of {@link AuthenticateMobileNoResponse }
     * 
     */
    public AuthenticateMobileNoResponse createAuthenticateMobileNoResponse() {
        return new AuthenticateMobileNoResponse();
    }

    /**
     * Create an instance of {@link AuthenticateMobileNoNew }
     * 
     */
    public AuthenticateMobileNoNew createAuthenticateMobileNoNew() {
        return new AuthenticateMobileNoNew();
    }

    /**
     * Create an instance of {@link AuthenticateMobileNoNewResponse }
     * 
     */
    public AuthenticateMobileNoNewResponse createAuthenticateMobileNoNewResponse() {
        return new AuthenticateMobileNoNewResponse();
    }

    /**
     * Create an instance of {@link FamilyMemberMapping }
     * 
     */
    public FamilyMemberMapping createFamilyMemberMapping() {
        return new FamilyMemberMapping();
    }

    /**
     * Create an instance of {@link FamilyMemberMappingResponse }
     * 
     */
    public FamilyMemberMappingResponse createFamilyMemberMappingResponse() {
        return new FamilyMemberMappingResponse();
    }

    /**
     * Create an instance of {@link FamilyMemberMappingNew }
     * 
     */
    public FamilyMemberMappingNew createFamilyMemberMappingNew() {
        return new FamilyMemberMappingNew();
    }

    /**
     * Create an instance of {@link FamilyMemberMappingNewResponse }
     * 
     */
    public FamilyMemberMappingNewResponse createFamilyMemberMappingNewResponse() {
        return new FamilyMemberMappingNewResponse();
    }

    /**
     * Create an instance of {@link DisplayFamilyMember }
     * 
     */
    public DisplayFamilyMember createDisplayFamilyMember() {
        return new DisplayFamilyMember();
    }

    /**
     * Create an instance of {@link DisplayFamilyMemberResponse }
     * 
     */
    public DisplayFamilyMemberResponse createDisplayFamilyMemberResponse() {
        return new DisplayFamilyMemberResponse();
    }

    /**
     * Create an instance of {@link DisplayFamilyMemberNew }
     * 
     */
    public DisplayFamilyMemberNew createDisplayFamilyMemberNew() {
        return new DisplayFamilyMemberNew();
    }

    /**
     * Create an instance of {@link DisplayFamilyMemberNewResponse }
     * 
     */
    public DisplayFamilyMemberNewResponse createDisplayFamilyMemberNewResponse() {
        return new DisplayFamilyMemberNewResponse();
    }

    /**
     * Create an instance of {@link ResendOTPMobile }
     * 
     */
    public ResendOTPMobile createResendOTPMobile() {
        return new ResendOTPMobile();
    }

    /**
     * Create an instance of {@link ResendOTPMobileResponse }
     * 
     */
    public ResendOTPMobileResponse createResendOTPMobileResponse() {
        return new ResendOTPMobileResponse();
    }

    /**
     * Create an instance of {@link PackageRecommendation }
     * 
     */
    public PackageRecommendation createPackageRecommendation() {
        return new PackageRecommendation();
    }

    /**
     * Create an instance of {@link PackageRecommendationResponse }
     * 
     */
    public PackageRecommendationResponse createPackageRecommendationResponse() {
        return new PackageRecommendationResponse();
    }

    /**
     * Create an instance of {@link SurveyForFamily }
     * 
     */
    public SurveyForFamily createSurveyForFamily() {
        return new SurveyForFamily();
    }

    /**
     * Create an instance of {@link SurveyForFamilyResponse }
     * 
     */
    public SurveyForFamilyResponse createSurveyForFamilyResponse() {
        return new SurveyForFamilyResponse();
    }

    /**
     * Create an instance of {@link SurveyCity }
     * 
     */
    public SurveyCity createSurveyCity() {
        return new SurveyCity();
    }

    /**
     * Create an instance of {@link SurveyCityResponse }
     * 
     */
    public SurveyCityResponse createSurveyCityResponse() {
        return new SurveyCityResponse();
    }

    /**
     * Create an instance of {@link OrderReportsCount }
     * 
     */
    public OrderReportsCount createOrderReportsCount() {
        return new OrderReportsCount();
    }

    /**
     * Create an instance of {@link OrderReportsCountResponse }
     * 
     */
    public OrderReportsCountResponse createOrderReportsCountResponse() {
        return new OrderReportsCountResponse();
    }

    /**
     * Create an instance of {@link GetACCList }
     * 
     */
    public GetACCList createGetACCList() {
        return new GetACCList();
    }

    /**
     * Create an instance of {@link GetACCListResponse }
     * 
     */
    public GetACCListResponse createGetACCListResponse() {
        return new GetACCListResponse();
    }

    /**
     * Create an instance of {@link GetCityDetails }
     * 
     */
    public GetCityDetails createGetCityDetails() {
        return new GetCityDetails();
    }

    /**
     * Create an instance of {@link GetCityDetailsResponse }
     * 
     */
    public GetCityDetailsResponse createGetCityDetailsResponse() {
        return new GetCityDetailsResponse();
    }

    /**
     * Create an instance of {@link GetGroupid }
     * 
     */
    public GetGroupid createGetGroupid() {
        return new GetGroupid();
    }

    /**
     * Create an instance of {@link GetGroupidResponse }
     * 
     */
    public GetGroupidResponse createGetGroupidResponse() {
        return new GetGroupidResponse();
    }

    /**
     * Create an instance of {@link CommonClass }
     * 
     */
    public CommonClass createCommonClass() {
        return new CommonClass();
    }

    /**
     * Create an instance of {@link CommonClassResponse }
     * 
     */
    public CommonClassResponse createCommonClassResponse() {
        return new CommonClassResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

}
