//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.30 at 06:58:36 PM IST 
//


package com.example.genericrestapi.createOrder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="P_ORDERNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_PAYMENT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_PAYMENT_DT" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="P_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="P_TRANS_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_PAYMENT_METHOD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_IPADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_PAYMENT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="P_PAYMENT_OPT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="grouptyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strVldTk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "porderno",
    "ppaymentid",
    "ppaymentdt",
    "pamount",
    "ptransid",
    "ppaymentmethod",
    "pipaddress",
    "ppaymentstatus",
    "ppaymentopt",
    "grouptyp",
    "source",
    "strVldTk"
})
@XmlRootElement(name = "PaymentStatus_Options")
public class PaymentStatusOptions {

    @XmlElement(name = "P_ORDERNO")
    protected String porderno;
    @XmlElement(name = "P_PAYMENT_ID")
    protected String ppaymentid;
    @XmlElement(name = "P_PAYMENT_DT")
    protected long ppaymentdt;
    @XmlElement(name = "P_AMOUNT")
    protected double pamount;
    @XmlElement(name = "P_TRANS_ID")
    protected String ptransid;
    @XmlElement(name = "P_PAYMENT_METHOD")
    protected String ppaymentmethod;
    @XmlElement(name = "P_IPADDRESS")
    protected String pipaddress;
    @XmlElement(name = "P_PAYMENT_STATUS")
    protected String ppaymentstatus;
    @XmlElement(name = "P_PAYMENT_OPT")
    protected String ppaymentopt;
    protected String grouptyp;
    protected String source;
    protected String strVldTk;

    /**
     * Gets the value of the porderno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORDERNO() {
        return porderno;
    }

    /**
     * Sets the value of the porderno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORDERNO(String value) {
        this.porderno = value;
    }

    /**
     * Gets the value of the ppaymentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPAYMENTID() {
        return ppaymentid;
    }

    /**
     * Sets the value of the ppaymentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPAYMENTID(String value) {
        this.ppaymentid = value;
    }

    /**
     * Gets the value of the ppaymentdt property.
     * 
     */
    public long getPPAYMENTDT() {
        return ppaymentdt;
    }

    /**
     * Sets the value of the ppaymentdt property.
     * 
     */
    public void setPPAYMENTDT(long value) {
        this.ppaymentdt = value;
    }

    /**
     * Gets the value of the pamount property.
     * 
     */
    public double getPAMOUNT() {
        return pamount;
    }

    /**
     * Sets the value of the pamount property.
     * 
     */
    public void setPAMOUNT(double value) {
        this.pamount = value;
    }

    /**
     * Gets the value of the ptransid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPTRANSID() {
        return ptransid;
    }

    /**
     * Sets the value of the ptransid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPTRANSID(String value) {
        this.ptransid = value;
    }

    /**
     * Gets the value of the ppaymentmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPAYMENTMETHOD() {
        return ppaymentmethod;
    }

    /**
     * Sets the value of the ppaymentmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPAYMENTMETHOD(String value) {
        this.ppaymentmethod = value;
    }

    /**
     * Gets the value of the pipaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIPADDRESS() {
        return pipaddress;
    }

    /**
     * Sets the value of the pipaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIPADDRESS(String value) {
        this.pipaddress = value;
    }

    /**
     * Gets the value of the ppaymentstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPAYMENTSTATUS() {
        return ppaymentstatus;
    }

    /**
     * Sets the value of the ppaymentstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPAYMENTSTATUS(String value) {
        this.ppaymentstatus = value;
    }

    /**
     * Gets the value of the ppaymentopt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPAYMENTOPT() {
        return ppaymentopt;
    }

    /**
     * Sets the value of the ppaymentopt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPAYMENTOPT(String value) {
        this.ppaymentopt = value;
    }

    /**
     * Gets the value of the grouptyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrouptyp() {
        return grouptyp;
    }

    /**
     * Sets the value of the grouptyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrouptyp(String value) {
        this.grouptyp = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the strVldTk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrVldTk() {
        return strVldTk;
    }

    /**
     * Sets the value of the strVldTk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrVldTk(String value) {
        this.strVldTk = value;
    }

}
