//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.30 at 06:58:36 PM IST 
//


package com.example.genericrestapi.createOrder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IN_TITLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_LAST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_DOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_AGE_YYY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_AGE_MM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_AGE_DD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_GENDER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_ADDRESS1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_ADDRESS2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_LANDMARK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_CITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_STATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_EMAIL_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_ZIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_DEVICE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_OSTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_OSVERSION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_MYSRLVER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IN_RELATIONSHIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="grouptyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strVldTk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "intitle",
    "infirstname",
    "inlastname",
    "indob",
    "inageyyy",
    "inagemm",
    "inagedd",
    "ingender",
    "inmobileno",
    "inaddress1",
    "inaddress2",
    "inlandmark",
    "incity",
    "instate",
    "incountry",
    "inemailid",
    "inzip",
    "indeviceid",
    "inostype",
    "inosversion",
    "inmysrlver",
    "inrelationship",
    "grouptyp",
    "source",
    "strVldTk"
})
@XmlRootElement(name = "UserRegistration")
public class UserRegistration {

    @XmlElement(name = "IN_TITLE")
    protected String intitle;
    @XmlElement(name = "IN_FIRST_NAME")
    protected String infirstname;
    @XmlElement(name = "IN_LAST_NAME")
    protected String inlastname;
    @XmlElement(name = "IN_DOB")
    protected String indob;
    @XmlElement(name = "IN_AGE_YYY")
    protected String inageyyy;
    @XmlElement(name = "IN_AGE_MM")
    protected String inagemm;
    @XmlElement(name = "IN_AGE_DD")
    protected String inagedd;
    @XmlElement(name = "IN_GENDER")
    protected String ingender;
    @XmlElement(name = "IN_MOBILE_NO")
    protected String inmobileno;
    @XmlElement(name = "IN_ADDRESS1")
    protected String inaddress1;
    @XmlElement(name = "IN_ADDRESS2")
    protected String inaddress2;
    @XmlElement(name = "IN_LANDMARK")
    protected String inlandmark;
    @XmlElement(name = "IN_CITY")
    protected String incity;
    @XmlElement(name = "IN_STATE")
    protected String instate;
    @XmlElement(name = "IN_COUNTRY")
    protected String incountry;
    @XmlElement(name = "IN_EMAIL_ID")
    protected String inemailid;
    @XmlElement(name = "IN_ZIP")
    protected String inzip;
    @XmlElement(name = "IN_DEVICE_ID")
    protected String indeviceid;
    @XmlElement(name = "IN_OSTYPE")
    protected String inostype;
    @XmlElement(name = "IN_OSVERSION")
    protected String inosversion;
    @XmlElement(name = "IN_MYSRLVER")
    protected String inmysrlver;
    @XmlElement(name = "IN_RELATIONSHIP")
    protected String inrelationship;
    protected String grouptyp;
    protected String source;
    protected String strVldTk;

    /**
     * Gets the value of the intitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTITLE() {
        return intitle;
    }

    /**
     * Sets the value of the intitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTITLE(String value) {
        this.intitle = value;
    }

    /**
     * Gets the value of the infirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFIRSTNAME() {
        return infirstname;
    }

    /**
     * Sets the value of the infirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFIRSTNAME(String value) {
        this.infirstname = value;
    }

    /**
     * Gets the value of the inlastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINLASTNAME() {
        return inlastname;
    }

    /**
     * Sets the value of the inlastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINLASTNAME(String value) {
        this.inlastname = value;
    }

    /**
     * Gets the value of the indob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDOB() {
        return indob;
    }

    /**
     * Sets the value of the indob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDOB(String value) {
        this.indob = value;
    }

    /**
     * Gets the value of the inageyyy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINAGEYYY() {
        return inageyyy;
    }

    /**
     * Sets the value of the inageyyy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINAGEYYY(String value) {
        this.inageyyy = value;
    }

    /**
     * Gets the value of the inagemm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINAGEMM() {
        return inagemm;
    }

    /**
     * Sets the value of the inagemm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINAGEMM(String value) {
        this.inagemm = value;
    }

    /**
     * Gets the value of the inagedd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINAGEDD() {
        return inagedd;
    }

    /**
     * Sets the value of the inagedd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINAGEDD(String value) {
        this.inagedd = value;
    }

    /**
     * Gets the value of the ingender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINGENDER() {
        return ingender;
    }

    /**
     * Sets the value of the ingender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINGENDER(String value) {
        this.ingender = value;
    }

    /**
     * Gets the value of the inmobileno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINMOBILENO() {
        return inmobileno;
    }

    /**
     * Sets the value of the inmobileno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINMOBILENO(String value) {
        this.inmobileno = value;
    }

    /**
     * Gets the value of the inaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINADDRESS1() {
        return inaddress1;
    }

    /**
     * Sets the value of the inaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINADDRESS1(String value) {
        this.inaddress1 = value;
    }

    /**
     * Gets the value of the inaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINADDRESS2() {
        return inaddress2;
    }

    /**
     * Sets the value of the inaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINADDRESS2(String value) {
        this.inaddress2 = value;
    }

    /**
     * Gets the value of the inlandmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINLANDMARK() {
        return inlandmark;
    }

    /**
     * Sets the value of the inlandmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINLANDMARK(String value) {
        this.inlandmark = value;
    }

    /**
     * Gets the value of the incity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCITY() {
        return incity;
    }

    /**
     * Sets the value of the incity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCITY(String value) {
        this.incity = value;
    }

    /**
     * Gets the value of the instate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTATE() {
        return instate;
    }

    /**
     * Sets the value of the instate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTATE(String value) {
        this.instate = value;
    }

    /**
     * Gets the value of the incountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCOUNTRY() {
        return incountry;
    }

    /**
     * Sets the value of the incountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCOUNTRY(String value) {
        this.incountry = value;
    }

    /**
     * Gets the value of the inemailid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINEMAILID() {
        return inemailid;
    }

    /**
     * Sets the value of the inemailid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINEMAILID(String value) {
        this.inemailid = value;
    }

    /**
     * Gets the value of the inzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINZIP() {
        return inzip;
    }

    /**
     * Sets the value of the inzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINZIP(String value) {
        this.inzip = value;
    }

    /**
     * Gets the value of the indeviceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDEVICEID() {
        return indeviceid;
    }

    /**
     * Sets the value of the indeviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDEVICEID(String value) {
        this.indeviceid = value;
    }

    /**
     * Gets the value of the inostype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINOSTYPE() {
        return inostype;
    }

    /**
     * Sets the value of the inostype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINOSTYPE(String value) {
        this.inostype = value;
    }

    /**
     * Gets the value of the inosversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINOSVERSION() {
        return inosversion;
    }

    /**
     * Sets the value of the inosversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINOSVERSION(String value) {
        this.inosversion = value;
    }

    /**
     * Gets the value of the inmysrlver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINMYSRLVER() {
        return inmysrlver;
    }

    /**
     * Sets the value of the inmysrlver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINMYSRLVER(String value) {
        this.inmysrlver = value;
    }

    /**
     * Gets the value of the inrelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINRELATIONSHIP() {
        return inrelationship;
    }

    /**
     * Sets the value of the inrelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINRELATIONSHIP(String value) {
        this.inrelationship = value;
    }

    /**
     * Gets the value of the grouptyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrouptyp() {
        return grouptyp;
    }

    /**
     * Sets the value of the grouptyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrouptyp(String value) {
        this.grouptyp = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the strVldTk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrVldTk() {
        return strVldTk;
    }

    /**
     * Sets the value of the strVldTk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrVldTk(String value) {
        this.strVldTk = value;
    }

}
